backend:
  name: github
  repo: jiangziyi333/huiven-history-club
  branch: main
  publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "活动纪实"
    folder: "content/posts"
    create: true
    preview: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "articles"
    label: "文章专栏"
    folder: "content/articles"
    create: true
    preview: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "作者", name: "author", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "videos"
    label: "视频专区"
    folder: "content/videos"
    create: true
    preview: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "B站嵌入代码", name: "bilibili", widget: "string"}
      - {label: "简介", name: "body", widget: "markdown"}

  - name: "members"
    label: "社员名录"
    folder: "content/members"
    create: true
    preview: true
    fields:
      - {label: "姓名", name: "title", widget: "string"}
      - {label: "职位", name: "position", widget: "string"}
      - {label: "个人简介", name: "body", widget: "markdown"}

  - name: "about"
    label: "关于我们"
    folder: "content/about"
    create: false
    fields:
      - {label: "社团介绍", name: "body", widget: "markdown"}